data_path: "/hpcdata/chi/PROJECTS_Archive/2022_CHI_PROPOSALS/Manthiram_Covid-tonsil_CHI-306/NEW_DATA_9_sept_2023/230908_A00941_1368_AHKVGVDSX2/RUN_23_306_3/RUN/NEW2_3AGGR/outs/count/filtered_feature_bc_matrix.h5"
lanes: [1, 2, 3, 4, 5, 6]
output_prefix: "306_3_release/B"
