data_path: "/hpcdata/chi/PROJECTS_Archive/2022_CHI_PROPOSALS/Manthiram_Covid-tonsil_CHI-306/306_4_MERGED_RUN3/aggr_2/outs/count/filtered_feature_bc_ma
trix.h5"
lanes: [5, 6, 13, 14, 21, 22]
output_prefix: "306_4_release/T4"
